import { StyleSheet } from "react-native";
import { APP_THEME as theme, UI_STYLES } from "@/src/styles/clubTheme";
export const styles = StyleSheet.create({
 screen: { flex: 1, backgroundColor: theme.colors.background },
 content: { width: "100%", maxWidth: 680, alignSelf: "center", padding: 16, paddingTop: 6, paddingBottom: 32, gap: 12 },
 row: { flexDirection: "row", flexWrap: "wrap", alignItems: "center", gap: 8 }, stack: { gap: 8 },
 metricsRow: { alignItems: "stretch" },
 // Supporting match cards retain their surface; summary sections have no nested outlines.
 card: { ...UI_STYLES.card, padding: 16, gap: 8, borderColor: "#E3DEE8", borderWidth: 1 },
 section: { gap: 8, paddingTop: 4 },
 title: { ...theme.text.section, color: theme.colors.text }, text: { ...theme.text.body, color: theme.colors.text },
 muted: { ...theme.text.body, color: theme.colors.muted }, link: { ...theme.text.body, color: theme.colors.primary, fontWeight: "600" },
 control: { minHeight: 44, paddingHorizontal: 12, paddingVertical: 10, justifyContent: "center" },
 periods: { flexDirection: "row", flexWrap: "wrap", padding: 3, gap: 2, borderRadius: 14, backgroundColor: "#EFEFF0" },
 period: { minHeight: 44, flexGrow: 1, paddingHorizontal: 8, paddingVertical: 8, borderRadius: 11, alignItems: "center", justifyContent: "center" },
 periodArrow: { width: 44, minHeight: 44, alignItems: "center", justifyContent: "center", borderRadius: 22, backgroundColor: theme.colors.hero },
 selected: { backgroundColor: theme.colors.primary }, selectedText: { color: theme.colors.onPrimary },
 selector: { minHeight: 44, minWidth: 0, flexGrow: 1, flexDirection: "row", alignItems: "center", gap: 8, paddingHorizontal: 12, paddingVertical: 8, borderWidth: 1, borderColor: "#D9D5DF", borderRadius: 12, backgroundColor: theme.colors.card },
 selectorValue: { ...theme.text.body, color: theme.colors.text, fontWeight: "600" },
 options: { backgroundColor: theme.colors.card, borderRadius: 12, padding: 4 },
 option: { minHeight: 44, padding: 12, justifyContent: "center" },
 summary: { backgroundColor: theme.colors.hero, borderRadius: 16, padding: 12, gap: 2 },
 metric: { minHeight: 64, flexGrow: 1, minWidth: 0, paddingVertical: 4, paddingHorizontal: 4, gap: 2 },
 value: { fontSize: 28, lineHeight: 36, fontWeight: "700", color: theme.colors.text },
 inlineValue: { ...theme.text.body, fontSize: 20, lineHeight: 28, fontWeight: "600", color: theme.colors.text },
 timeLine: { minHeight: 44, paddingVertical: 4, paddingHorizontal: 4, gap: 2, borderTopWidth: 1, borderTopColor: "#DBD3E8" },
 inlineAction: { minHeight: 44, flexDirection: "row", alignItems: "center", flexWrap: "wrap", gap: 8, paddingVertical: 8, paddingHorizontal: 4 },
 rate: { minHeight: 44, flexDirection: "row", flexWrap: "wrap", alignItems: "center", gap: 12, paddingVertical: 8, borderTopWidth: 1, borderTopColor: "#E6E1E9" },
 rateValue: { fontSize: 26, lineHeight: 34, fontWeight: "700", color: theme.colors.primary },
 input: { ...UI_STYLES.field }, gameRow: { flexDirection: "row", alignItems: "center", gap: 12, paddingVertical: 10, minHeight: 60 },
 gameName: { ...theme.text.body, fontWeight: "700", color: theme.colors.text }, cover: { width: 60, height: 60 },
 grow: { flex: 1, minWidth: 0, gap: 4 },
});
